### ISSUE TITLE
Is this real?

### ISSUE THREAD

**Issue by KneesDev** [silvanohirtie/Discord-Token-Generator#10]
Is this **Discord Token Generator** real and working or just generating random letters?
This is my **question..**

**Comment by silvanohirtie** [comment]
You cannot generate real discord tokens, this tool just uses the discord's
token syntax to create some random ones, then the checker check if they're
working or not

Il giorno mar 29 dic 2020 alle ore 15:17 Nikos Komninos <
notifications@github.com> ha scritto:

**Comment by DmitrijVC** [comment]
As silvanohirtie mentioned, it creates a random token, but probability of it being valid (used by an existing account) is so low that it's basically 0% 

_(or my math is just really bad)_

**Comment by silvanohirtie** [comment]
> As silvanohirtie mentioned, it creates a random token, but probability of it being valid (used by an existing account) is so low that it's basically 0%
> 
> _(or my math is just really bad)_

You're not wrong, it is technically really really hard to get working tokens since there are really a lot of combinations for discord tokens, but it's still better than trying to manually get them
