### ISSUE TITLE
$ko^zvl*xH7b9hDRxi_4Tx^OIbq4xL2c

### ISSUE THREAD

**Issue by pxladin** [silvanohirtie/Discord-Token-Generator#17]

**Comment by h1v3m1ndAnon** [comment]
Source? It may be possible to use a wordlist of known user ID's to assist it.

**Comment by pxladin** [comment]
> Source? It may be possible to use a wordlist of known user ID's to assist it.

i got it from the official discord api server, just go in there and type ?tag token in the channel "playground" 
(link: https://discord.gg/discord-api)
