### ISSUE TITLE
Idea: (I know this is in the issues tab but I'm kinda new to github)

### ISSUE THREAD

**Issue by TheMaligator** [silvanohirtie/Discord-Token-Generator#6]
You should add more token types to generate user tokens also, I believe they mostly start with "Nzg4Nj" here is an example one from a random account I created Nzg4NjkxNTI0NjMxMTM0MjM5.X9nMbQ.3rvyZgpwn-CFCV0bqw1ax8RquMw (don't worry, this account is completely useless) and when I made 6 tokens, they all started with "Nzg4Nj". Please consider using this idea, and if you want to work on this with me, my discord username is: The Maligator#9760 If you want, I could also send you more tokens so you could see how they look. Thank you.

**Comment by HenryLeC** [comment]
Hey, I am not here to way in on the idea, but the issues tab is the right place to put ideas. You just need to tag it as a feature request

**Comment by silvanohirtie** [comment]
oh thanks, I will implement that

Il giorno gio 17 dic 2020 alle 21:35 Henry LeCompte <
notifications@github.com> ha scritto:

**Comment by FloppyT** [comment]
Hey there, btw the first section of a discord token is just the user's id base64 encoded - that should help you in your investigations
